### ISSUE TITLE
[Enhancement] Please upload at F-Droid

### ISSUE THREAD

**Issue by AhmedNazir** [SongTube/SongTube-App#40]

**Comment by shuvashish76** [comment]
Thanks to @IzzySoft the app now available on [izzy-repo](https://apt.izzysoft.de/fdroid/index/apk/com.artxdev.songtube), initially requested [here](https://gitlab.com/IzzyOnDroid/repo/-/issues/229).

F-Droid MR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8419

Important to mention thoughts of @Artx-II : https://github.com/SongTube/SongTube-App/pull/47#issuecomment-786384465

Dupe #79

**Comment by Artx-II** [comment]
That's awesome, I'm closing this issue then.

**Comment by licaon-kter** [comment]
this is not completed lol

```
Builds:
  - versionName: 7.3.2
    versionCode: 5200
    commit: fd402867a4d3122d870462bd19eff275ad46bc2b
    output: build/app/outputs/apk/release/app-release.apk
    srclibs:
      - flutter@3.19.4
    prebuild:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter config --no-analytics
      - $$flutter$$/bin/flutter pub get
    scandelete:
      - .pub-cache
    build:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter build apk
```

fails as:
```
...
.pub-cache/hosted/pub.dev/fwfh_text_style-2.22.08+1/lib/fwfh_text_style.dart:253:21: Error: The method '_TextStyleProxy.getPara
graphStyle' doesn't have the named parameter 'textScaler' of overridden method 'TextStyle.getParagraphStyle'.
  ui.ParagraphStyle getParagraphStyle({
                    ^
../srclib/flutter/packages/flutter/lib/src/painting/text_style.dart:1349:21: Context: This is the overridden method ('getParagr
aphStyle').
  ui.ParagraphStyle getParagraphStyle({
                    ^
.pub-cache/hosted/pub.dev/fwfh_text_style-2.22.08+1/lib/fwfh_text_style.dart:285:16: Error: The method '_TextStyleProxy.getText
Style' has fewer named arguments than those of overridden method 'TextStyle.getTextStyle'.
  ui.TextStyle getTextStyle({double textScaleFactor = 1.0}) =>
               ^
../srclib/flutter/packages/flutter/lib/src/painting/text_style.dart:1294:16: Context: This is the overridden method ('getTextSt
yle').
  ui.TextStyle getTextStyle({
               ^
lib/providers/download_provider.dart:149:17: Error: Member not found: 'AudioTagger.updateMediaStore'.
    AudioTagger.updateMediaStore(song.id);
                ^^^^^^^^^^^^^^^^
lib/screens/id3_editor.dart:716:34: Error: Member not found: 'AudioTagger.updateMediaStore'.
              tagger.AudioTagger.updateMediaStore(widget.song.id);
                                 ^^^^^^^^^^^^^^^^
.pub-cache/hosted/pub.dev/fwfh_text_style-2.22.08+1/lib/fwfh_text_style.dart:271:9: Error: No named parameter with the name 'te
xtScaleFactor'.
        textScaleFactor: textScaleFactor,
        ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
```

which Flutter version was used for https://github.com/SongTube/SongTube-App/releases/tag/7.3.2%2B5200 ?
